### PR TITLE
Update OXID eShop Coding Standards Definition for CodeSniffer 2.1.0

### PR DESCRIPTION
**Pull request by sd-tm**
I have updated OXID eShop Coding Standards Definition for CodeSniffer 2.1.0 that include `phpcbf`

### CODE REVIEW

**Comment by kermie** [comment]
Thanks alot. We'll check your contribution as soon as we have some time left for it. Please try to manage to send your signed OCA in the mean time. Cheers!

**Comment by sd-tm** [comment]
Okay i have agreed the OCA :+1:

**Comment by sd-tm** [comment]
Okay i have agreed the OCA :+1:

**Comment by kermie** [comment]
Got it :+1: 
Did you use a type writer to fill the form? :D

**Comment by sd-tm** [comment]
Perfect :-)
Yes sure the type writer machine: MacOS Yosemite -> Preview App

**Comment by sd-tm** [comment]
We have found a Bug with the return statmenet in a closure. That is now fix it in commit (a61bc31)

**Comment by artsev-oxid** [comment]
Hi @sd-tm, 
I need more time for investigation before accepting this one, hang on.
Sorry for the inconvenience.

**Comment by Sieg** [comment]
Hello, I just tried your commit, and found some problems: its not working with 2.1 CodeSniffer, but works with 2.2 version, so could you please check/update it?. Other problem is - new version generates a lot of notices, could you please check it with display_errors and error_reporting turned on?. Notice example:
>PHP Notice:  Undefined index: scope_opener in .../Standards/Oxid/Sniffs/Commenting/FunctionCommentSniff.php on line 104
>PHP Notice:  Undefined index: scope_closer in .../Standards/Oxid/Sniffs/Commenting/FunctionCommentSniff.php on line 106
>PHP Notice:  Undefined index:  in .../File.php on line 3247

**Pull request merged**
